services:
  api:
    container_name: c-shopping
    build: .
    ports:
      - "8004:8004"
    environment:
      PORT: 8004
      DB_URL: mongodb://c-shopping-db:27017/shopping
      APP_SECRET: dev-secret-change-me
      CUSTOMERS_URL: http://c-customers:8003
      PRODUCTS_URL: http://c-products:8002
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - shopping-db
    networks:
      - microservices-network

  shopping-db:
    container_name: c-shopping-db
    image: mongo:7
    ports:
      - "27019:27017"
    volumes:
      - shopping-data:/data/db
    networks:
      - microservices-network

volumes:
  shopping-data:

networks:
  microservices-network:
    external: true